json.id product.id
json.name product.name_list
json.price product.price
json.quantity product.quantity
json.in_stock product.in_stock
json.is_discounted product.is_discounted
json.tax product.tax
json.total product.total
json.created_at product.friendly_created_at
json.description product.description
json.supplier_id product.supplier_id
